import React from 'react';
import Sidebar from './_components/sidebar';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WebsiteLayout({ children }) {
  return (
    <div className="flex">
      <Sidebar />
      <div className="content pl-[270px] w-[100%]">
        {children}
      </div>
    </div>
  );
}
