"use client"
import React, { useEffect, useState } from 'react';
import Sidebar from './_components/sidebar';
import { usePathname } from 'next/navigation';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function WebsiteLayout({ children }) {
  const pathname = usePathname();
  const [show, setShow] = useState(false)

  useEffect(() => {
    const pathSegments = pathname.split("/");
    const lastSegment = pathSegments[pathSegments.length - 2];
    setShow(lastSegment !== "quotes")
  }, [pathname]);


  return (
    <div className="flex">
      {
        show && <Sidebar />
      }
      <div className={`content w-[100%] ${show ? 'pl-[270px]' : ''}`}>
        {children}
      </div>
    </div>
  );
}
